### ISSUE TITLE
IRF9520 being used out of spec

### ISSUE THREAD

**Issue by dazwin** [ostaquet/Arduino-Nano-33-IoT-Ultimate-Guide#10]
The RTC method uses an IRF9520, which requires a gate-source voltage of -10V. So, at -6.5V it's being used out of spec. I believe it will work in most cases (not an expert!) but given this is a tutorial I think it should at least be pointed out.

P-Channel MOSFETs that operate at logic level are hard to come by (certainly as THT). I see you changed this from a low-side driver not long ago, so curious why the change - easier circuit, or to eliminate the BJT?

Great page - very useful!

**Comment by ostaquet** [comment]
Hi @dazwin,

Thanks for your note! I'm not an electronic expert neither. I'm solving my day-to-day issues in my personal projects ;-)

I moved from low-side driver to high-side driver because of a discussion on another forum regarding the potential issue of having a "floating" ground. I found the point valid (even if the tone of the discussion wasn't :-D).

By moving on high-side, I tried to find a way to simplify the design and I decided to drive the power of the Arduino with a single MOSFET. I had IRF9520 in the stock, so, I used it.

I don't get your point regarding the out of spec as the gate-source threshold voltage is between -2V and -4V which is OK to be piloted by -5V coming from the voltage regulator (pull-up) and the pull-down from the interrupt pin of the DS3231.

The only thing that I'm not happy with this design is that I have to power with 6.5V minimum to get around 5.2V/5.3V at the Vin of the Nano. If the Vin is below 5V, the Wifi is not stable on the Nano. I would like to have only 5V power for the all design with no regulator but I didn't figure out how to made it due to the MOSFET.

KR
